[tox]
min_version = 4.22
envlist =
    py39-lektor33
    py{310,311,312,313,314}{,-lektor33}


[testenv]
dependency_groups = dev
commands =
    pytest {posargs}
set_env =
    # Put coverage files in .tox/py3xx/
    COVERAGE_FILE = {env_dir}{/}.coverage
    COVERAGE_HTML_DIR = {env_dir}{/}htmlcov
deps =
    lektor33: lektor == 3.*
    !lektor33: lektor >= 3.4.0b1
