---
name: "CI"

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '10 3 * * 1'

env:
  TOX_COLORED: yes

jobs:
  tests:
    name: "${{ matrix.os }} py${{ matrix.python-version }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
    permissions:
      contents: read
      actions: read
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: "Run tox targets for py${{ matrix.python-version }} on ${{ matrix.os }}"
        env:
          PYTHON_VERSION: "${{ matrix.python-version }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v -f "py${PYTHON_VERSION//./}" -- -v --color=yes
