---
name: "CI"

on:
  push:
  schedule:
    - cron: '10 3 * * 1'

jobs:
  tests:
    name: "${{ matrix.tox-envs }} with ${{ matrix.python-version }}"
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37"
          - python-version: "3.8"
            os: "ubuntu-latest"
            tox-envs: "py38"
          - python-version: "3.9"
            os: "ubuntu-latest"
            tox-envs: "py39"
          - python-version: "3.10"
            os: "ubuntu-latest"
            tox-envs: "py310"
          - python-version: "3.11"
            os: "ubuntu-latest"
            tox-envs: "py311"

    env:
      PY_COLORS: 1

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel tox
      - name: "Run tox targets for ${{ matrix.tox-envs }} with ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes

  pre-tests:
    name: "PIP_PRE=1 ${{ matrix.tox-envs }} with ${{ matrix.python-version }}"
    strategy:
      matrix:
        include:
          - python-version: "3.7"
            os: "ubuntu-latest"
            tox-envs: "py37"
          - python-version: "3.8"
            os: "ubuntu-latest"
            tox-envs: "py38"
          - python-version: "3.9"
            os: "ubuntu-latest"
            tox-envs: "py39"
          - python-version: "3.10"
            os: "ubuntu-latest"
            tox-envs: "py310"
          - python-version: "3.11"
            os: "ubuntu-latest"
            tox-envs: "py311"

    env:
      PY_COLORS: 1

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe -o nounset
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel tox
      - name: "Run tox targets for ${{ matrix.tox-envs }} with ${{ matrix.python-version }} on ${{ matrix.os }}"
        continue-on-error: true
        run: |
          set -xe -o nounset
          python -m tox -a -vv
          PIP_PRE=1 python -m tox -v -e ${{ matrix.tox-envs }} -- -v --color=yes
